{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs.zeil",
    "module": "code-grader",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "code-grader-1.2.1.jar",
          "url": "code-grader-1.2.1.jar",
          "size": 120345,
          "sha512": "320c36df95131447b127991b5d4e2e8d26ad48879d57804b5d3f470029c9ba1b6c4b351d1c100f89e175a9b21f9a04bb8ec2f41c87f0bf75852410086cd3d244",
          "sha256": "390053c2a3bf292de7010b0bd4e48df2289eb04dd2fefa6bdf2bceadb0c533d7",
          "sha1": "66c59116234007995d9dd981eb2b8b4c65e52844",
          "md5": "ae880ee4f89e5bbb78c0f585a874a3c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "5.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "code-grader-1.2.1.jar",
          "url": "code-grader-1.2.1.jar",
          "size": 120345,
          "sha512": "320c36df95131447b127991b5d4e2e8d26ad48879d57804b5d3f470029c9ba1b6c4b351d1c100f89e175a9b21f9a04bb8ec2f41c87f0bf75852410086cd3d244",
          "sha256": "390053c2a3bf292de7010b0bd4e48df2289eb04dd2fefa6bdf2bceadb0c533d7",
          "sha1": "66c59116234007995d9dd981eb2b8b4c65e52844",
          "md5": "ae880ee4f89e5bbb78c0f585a874a3c2"
        }
      ]
    }
  ]
}
