{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs.zeil",
    "module": "code-grader",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "code-grader-1.2.1.jar",
          "url": "code-grader-1.2.1.jar",
          "size": 120345,
          "sha512": "82bc98068b8780aa96b9c9f8e5f89c0e1e0dbbd7ee3085b878bfa6a135a3b6f26b0c96211b0afbfb1a6e926e1c776fbc3273c536139cb2b0affd7d49a5ccaa43",
          "sha256": "9348989f67426cc9d057333d8ac0446e52d39e8f209ade053819a6183fa6ffbb",
          "sha1": "f4e1163abb0656eb10a28d0f627909c6a00b4bb4",
          "md5": "2984c60eb6fd5afe511ee4f33380fe9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "5.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "code-grader-1.2.1.jar",
          "url": "code-grader-1.2.1.jar",
          "size": 120345,
          "sha512": "82bc98068b8780aa96b9c9f8e5f89c0e1e0dbbd7ee3085b878bfa6a135a3b6f26b0c96211b0afbfb1a6e926e1c776fbc3273c536139cb2b0affd7d49a5ccaa43",
          "sha256": "9348989f67426cc9d057333d8ac0446e52d39e8f209ade053819a6183fa6ffbb",
          "sha1": "f4e1163abb0656eb10a28d0f627909c6a00b4bb4",
          "md5": "2984c60eb6fd5afe511ee4f33380fe9d"
        }
      ]
    }
  ]
}
