{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs",
    "module": "cowem-plugin",
    "version": "1.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cowem-plugin-1.25.0.jar",
          "url": "cowem-plugin-1.25.0.jar",
          "size": 1590400,
          "sha512": "fb24f8845dc38134fd31fc87bccecd3350b8806a2f03a7350bf7192bd63cd80276f97d25de9f85c3a434720fb56b7f21969119d9db1eefe849f6ee7cedc950a8",
          "sha256": "3bccf2bf2b01a236e06967044aad5983618a1ada55fcd0c9ff4fb78828a11658",
          "sha1": "d576c299229b02d4d4f555de0a79cb11ee85c9c4",
          "md5": "6fb63ec36d45fc27bb764aba943208cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hidetake",
          "module": "gradle-ssh-plugin",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.pegdown",
          "module": "pegdown",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "net.sf.saxon",
          "module": "Saxon-HE",
          "version": {
            "requires": "11.4"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.4.0.202211300538-r"
          }
        }
      ],
      "files": [
        {
          "name": "cowem-plugin-1.25.0.jar",
          "url": "cowem-plugin-1.25.0.jar",
          "size": 1590400,
          "sha512": "fb24f8845dc38134fd31fc87bccecd3350b8806a2f03a7350bf7192bd63cd80276f97d25de9f85c3a434720fb56b7f21969119d9db1eefe849f6ee7cedc950a8",
          "sha256": "3bccf2bf2b01a236e06967044aad5983618a1ada55fcd0c9ff4fb78828a11658",
          "sha1": "d576c299229b02d4d4f555de0a79cb11ee85c9c4",
          "md5": "6fb63ec36d45fc27bb764aba943208cc"
        }
      ]
    }
  ]
}
