{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs",
    "module": "cowem-plugin",
    "version": "1.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cowem-plugin-1.25.0.jar",
          "url": "cowem-plugin-1.25.0.jar",
          "size": 1590070,
          "sha512": "a264ad5f9310ec3e588618b19de3be8acb314da50970766b53a371a2538d2df83367bdee098100033617bc518e0d87cdc66958ddac738a6ef08ece3a96e9d8d5",
          "sha256": "b97dfddd75913a9234140922b14b0ab3ca5777d3058e8ebe852fd21467cb04d3",
          "sha1": "7a0f3f801fca44389423ecafa03d84bbc85ab78a",
          "md5": "22b510b9bfeea38e3a5a741ded849763"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hidetake",
          "module": "gradle-ssh-plugin",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.pegdown",
          "module": "pegdown",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "net.sf.saxon",
          "module": "Saxon-HE",
          "version": {
            "requires": "11.4"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.4.0.202211300538-r"
          }
        }
      ],
      "files": [
        {
          "name": "cowem-plugin-1.25.0.jar",
          "url": "cowem-plugin-1.25.0.jar",
          "size": 1590070,
          "sha512": "a264ad5f9310ec3e588618b19de3be8acb314da50970766b53a371a2538d2df83367bdee098100033617bc518e0d87cdc66958ddac738a6ef08ece3a96e9d8d5",
          "sha256": "b97dfddd75913a9234140922b14b0ab3ca5777d3058e8ebe852fd21467cb04d3",
          "sha1": "7a0f3f801fca44389423ecafa03d84bbc85ab78a",
          "md5": "22b510b9bfeea38e3a5a741ded849763"
        }
      ]
    }
  ]
}
