{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs",
    "module": "cowem-plugin",
    "version": "1.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cowem-plugin-1.25.0.jar",
          "url": "cowem-plugin-1.25.0.jar",
          "size": 1587771,
          "sha512": "d21346121020c722963c34b2850c2aee10a3f9f7400d8f052465bcfac760ab63a3009e49ee74d5095b4c9388837060e52f10c22fbbd30f5174d79cf1cafb5e0b",
          "sha256": "6d7561b978fd2b8604c3d8e434a754458c4b92985ca1271469c7496358733754",
          "sha1": "9e6ba4a882223b49b56ec1024d38bcf7e4793d27",
          "md5": "5d836357af00e295aff6aed4f8b38e82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hidetake",
          "module": "gradle-ssh-plugin",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.pegdown",
          "module": "pegdown",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "net.sf.saxon",
          "module": "Saxon-HE",
          "version": {
            "requires": "11.4"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.4.0.202211300538-r"
          }
        }
      ],
      "files": [
        {
          "name": "cowem-plugin-1.25.0.jar",
          "url": "cowem-plugin-1.25.0.jar",
          "size": 1587771,
          "sha512": "d21346121020c722963c34b2850c2aee10a3f9f7400d8f052465bcfac760ab63a3009e49ee74d5095b4c9388837060e52f10c22fbbd30f5174d79cf1cafb5e0b",
          "sha256": "6d7561b978fd2b8604c3d8e434a754458c4b92985ca1271469c7496358733754",
          "sha1": "9e6ba4a882223b49b56ec1024d38bcf7e4793d27",
          "md5": "5d836357af00e295aff6aed4f8b38e82"
        }
      ]
    }
  ]
}
