{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs",
    "module": "cowem-plugin",
    "version": "1.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cowem-plugin-1.25.1.jar",
          "url": "cowem-plugin-1.25.1.jar",
          "size": 1590764,
          "sha512": "6090aa622c8c88266a96ee952542876b90e582f7b03d31a66a979ce4bef2499b7fa685d6498b156db5b69d9be5b1ea60a51480e487fab18ca593ed12cba48a9e",
          "sha256": "0860d896157529cdcd0eb3d77111acf4506d0a73a7294e9da1cf290c3a24f09a",
          "sha1": "3ab88ad0c1ea6752025885341065a37893c5140a",
          "md5": "4cc1c0f5a7c15f471ac60d8a6317a4d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hidetake",
          "module": "gradle-ssh-plugin",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.pegdown",
          "module": "pegdown",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "net.sf.saxon",
          "module": "Saxon-HE",
          "version": {
            "requires": "11.4"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.4.0.202211300538-r"
          }
        }
      ],
      "files": [
        {
          "name": "cowem-plugin-1.25.1.jar",
          "url": "cowem-plugin-1.25.1.jar",
          "size": 1590764,
          "sha512": "6090aa622c8c88266a96ee952542876b90e582f7b03d31a66a979ce4bef2499b7fa685d6498b156db5b69d9be5b1ea60a51480e487fab18ca593ed12cba48a9e",
          "sha256": "0860d896157529cdcd0eb3d77111acf4506d0a73a7294e9da1cf290c3a24f09a",
          "sha1": "3ab88ad0c1ea6752025885341065a37893c5140a",
          "md5": "4cc1c0f5a7c15f471ac60d8a6317a4d9"
        }
      ]
    }
  ]
}
