{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs",
    "module": "cowem-plugin",
    "version": "1.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cowem-plugin-1.25.1.jar",
          "url": "cowem-plugin-1.25.1.jar",
          "size": 1563055,
          "sha512": "7573739d71359ef0e9b2359ff6d7d47182f0e44078448949c7752cb77f8d78ba3398ded9d30d79b96f6b622af9fa9b22d3907f72366ad14afec99e7c639d2a11",
          "sha256": "f0695acd656a507a4dc9685a6bfa07ef3d378ec9a6a3a9199df235d268189a99",
          "sha1": "3900ba4f4ab8855e68bd556d8ad47afabe59fa8a",
          "md5": "38ce50c7a505c3c285bea104f7fe823b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hidetake",
          "module": "gradle-ssh-plugin",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.pegdown",
          "module": "pegdown",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "net.sf.saxon",
          "module": "Saxon-HE",
          "version": {
            "requires": "11.4"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.4.0.202211300538-r"
          }
        }
      ],
      "files": [
        {
          "name": "cowem-plugin-1.25.1.jar",
          "url": "cowem-plugin-1.25.1.jar",
          "size": 1563055,
          "sha512": "7573739d71359ef0e9b2359ff6d7d47182f0e44078448949c7752cb77f8d78ba3398ded9d30d79b96f6b622af9fa9b22d3907f72366ad14afec99e7c639d2a11",
          "sha256": "f0695acd656a507a4dc9685a6bfa07ef3d378ec9a6a3a9199df235d268189a99",
          "sha1": "3900ba4f4ab8855e68bd556d8ad47afabe59fa8a",
          "md5": "38ce50c7a505c3c285bea104f7fe823b"
        }
      ]
    }
  ]
}
