{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs",
    "module": "cowem-plugin",
    "version": "1.22.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cowem-plugin-1.22.6.jar",
          "url": "cowem-plugin-1.22.6.jar",
          "size": 1610982,
          "sha512": "dee15aa3de95ee98f95f259100d826ceb0c5840f033032e7e728a7ce4bf49d9698225ca0ec7c56032b529253124e6edddcb606dbefadf90ec1927def5a9b9f19",
          "sha256": "aa2d39e1e36dae1ec853242714d3292a3524868bbe53669709e8197dbb44d717",
          "sha1": "45a91cdfd6b7262a7726c44ff997149d30b36718",
          "md5": "5909a67109c48aa4fcdb6d02135220df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hidetake",
          "module": "gradle-ssh-plugin",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.pegdown",
          "module": "pegdown",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "net.sf.saxon",
          "module": "Saxon-HE",
          "version": {
            "requires": "11.4"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.4.0.202211300538-r"
          }
        }
      ],
      "files": [
        {
          "name": "cowem-plugin-1.22.6.jar",
          "url": "cowem-plugin-1.22.6.jar",
          "size": 1610982,
          "sha512": "dee15aa3de95ee98f95f259100d826ceb0c5840f033032e7e728a7ce4bf49d9698225ca0ec7c56032b529253124e6edddcb606dbefadf90ec1927def5a9b9f19",
          "sha256": "aa2d39e1e36dae1ec853242714d3292a3524868bbe53669709e8197dbb44d717",
          "sha1": "45a91cdfd6b7262a7726c44ff997149d30b36718",
          "md5": "5909a67109c48aa4fcdb6d02135220df"
        }
      ]
    }
  ]
}
