{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs",
    "module": "cowem-plugin",
    "version": "1.22.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cowem-plugin-1.22.6.jar",
          "url": "cowem-plugin-1.22.6.jar",
          "size": 1611008,
          "sha512": "d0e7ae4fff393516c6e3f046272dba63acc9a8465529010c32a8e26c6bc084bd42373fdf968eefc0572e83af376f00a9d79a8e95f641923e99f8d8ce1b1616fd",
          "sha256": "78837bbf8f293188835e91da04cc3a1292b61d08835d55bcd6b9e67629b0c009",
          "sha1": "4805fcddaae8cb6a3f64c484a0df881ff049d82c",
          "md5": "1b2ce5361e9e15845da0f68184602ffe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hidetake",
          "module": "gradle-ssh-plugin",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.pegdown",
          "module": "pegdown",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "net.sf.saxon",
          "module": "Saxon-HE",
          "version": {
            "requires": "11.4"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.4.0.202211300538-r"
          }
        }
      ],
      "files": [
        {
          "name": "cowem-plugin-1.22.6.jar",
          "url": "cowem-plugin-1.22.6.jar",
          "size": 1611008,
          "sha512": "d0e7ae4fff393516c6e3f046272dba63acc9a8465529010c32a8e26c6bc084bd42373fdf968eefc0572e83af376f00a9d79a8e95f641923e99f8d8ce1b1616fd",
          "sha256": "78837bbf8f293188835e91da04cc3a1292b61d08835d55bcd6b9e67629b0c009",
          "sha1": "4805fcddaae8cb6a3f64c484a0df881ff049d82c",
          "md5": "1b2ce5361e9e15845da0f68184602ffe"
        }
      ]
    }
  ]
}
