{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs.zeil",
    "module": "code-grader",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "code-grader-1.3.1.jar",
          "url": "code-grader-1.3.1.jar",
          "size": 122909,
          "sha512": "92aa9c27e186e6a0c75ec99fe4daf947fd1d63f04bd2400e0655e882685e95d770eace938ed6ce66a92590eb46b43d447464db988d89fabb224d5edaf7139039",
          "sha256": "d949f6294d90797e07f5dd42a8028e17146c8a0b23771d773ff455bbff8b6aac",
          "sha1": "8da44931f6386694640af73b13760660571ff1c4",
          "md5": "188823b2f9c119a7bb4d3245344d4a51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "5.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "code-grader-1.3.1.jar",
          "url": "code-grader-1.3.1.jar",
          "size": 122909,
          "sha512": "92aa9c27e186e6a0c75ec99fe4daf947fd1d63f04bd2400e0655e882685e95d770eace938ed6ce66a92590eb46b43d447464db988d89fabb224d5edaf7139039",
          "sha256": "d949f6294d90797e07f5dd42a8028e17146c8a0b23771d773ff455bbff8b6aac",
          "sha1": "8da44931f6386694640af73b13760660571ff1c4",
          "md5": "188823b2f9c119a7bb4d3245344d4a51"
        }
      ]
    }
  ]
}
