{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs",
    "module": "cowem-plugin",
    "version": "1.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cowem-plugin-1.23.0.jar",
          "url": "cowem-plugin-1.23.0.jar",
          "size": 1611757,
          "sha512": "adc6aec0063101c4682b75a27a25789eac2350c865349271b360c132c7ef9c8e53e683adf840cc19dca239db6b1908b7e7621163303abfb690ff66edf1b3cfe9",
          "sha256": "4c8f66850b4c7148d64861fe449b78399319c24434db0bbbc2499c5d3594c48d",
          "sha1": "67ba5e84c140d440ca7cb0409d8f7f88eb8f62c1",
          "md5": "43a47e0f31fbbcb7da926f5f23db0e38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hidetake",
          "module": "gradle-ssh-plugin",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.pegdown",
          "module": "pegdown",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "net.sf.saxon",
          "module": "Saxon-HE",
          "version": {
            "requires": "11.4"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.4.0.202211300538-r"
          }
        }
      ],
      "files": [
        {
          "name": "cowem-plugin-1.23.0.jar",
          "url": "cowem-plugin-1.23.0.jar",
          "size": 1611757,
          "sha512": "adc6aec0063101c4682b75a27a25789eac2350c865349271b360c132c7ef9c8e53e683adf840cc19dca239db6b1908b7e7621163303abfb690ff66edf1b3cfe9",
          "sha256": "4c8f66850b4c7148d64861fe449b78399319c24434db0bbbc2499c5d3594c48d",
          "sha1": "67ba5e84c140d440ca7cb0409d8f7f88eb8f62c1",
          "md5": "43a47e0f31fbbcb7da926f5f23db0e38"
        }
      ]
    }
  ]
}
