{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs.zeil",
    "module": "code-grader",
    "version": "1.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "code-grader-1.2.5.jar",
          "url": "code-grader-1.2.5.jar",
          "size": 120716,
          "sha512": "4a61a0b122c129b05f3aa901b699cb71b0e2d8ed02ba68b096e11c1275d5a1c35021b3f438a664984fcc9d2d0a4f177d12ff31df087274b93421ec42c84935de",
          "sha256": "24837eb6d589869423071523f8053077e8701bab11b036c429a60526e02175e5",
          "sha1": "400f73aa444c049259179b3ff61492d866b56ecc",
          "md5": "5e5061f88909edd45c0af78798870db0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "5.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "code-grader-1.2.5.jar",
          "url": "code-grader-1.2.5.jar",
          "size": 120716,
          "sha512": "4a61a0b122c129b05f3aa901b699cb71b0e2d8ed02ba68b096e11c1275d5a1c35021b3f438a664984fcc9d2d0a4f177d12ff31df087274b93421ec42c84935de",
          "sha256": "24837eb6d589869423071523f8053077e8701bab11b036c429a60526e02175e5",
          "sha1": "400f73aa444c049259179b3ff61492d866b56ecc",
          "md5": "5e5061f88909edd45c0af78798870db0"
        }
      ]
    }
  ]
}
