{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs.zeil",
    "module": "code-grader",
    "version": "1.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "code-grader-1.2.5.jar",
          "url": "code-grader-1.2.5.jar",
          "size": 121101,
          "sha512": "e5d9e0014f64f289321b5b1213e7bf6c8a816b06e6f412c47c05bc45a5ea3dd7add4ff44b3a3f1b6dcb10a730febbf25b23ea7aedea0cf8c360c2c47134959d2",
          "sha256": "5017b4c6ed08e0d101a5946b0ad108ece04d4e66073633824afa70653dbc5fa4",
          "sha1": "b26053546fff009761942cbbcc4423a3a43cc153",
          "md5": "a040f994623a3f8eeb48cfa29a28a7c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "5.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "code-grader-1.2.5.jar",
          "url": "code-grader-1.2.5.jar",
          "size": 121101,
          "sha512": "e5d9e0014f64f289321b5b1213e7bf6c8a816b06e6f412c47c05bc45a5ea3dd7add4ff44b3a3f1b6dcb10a730febbf25b23ea7aedea0cf8c360c2c47134959d2",
          "sha256": "5017b4c6ed08e0d101a5946b0ad108ece04d4e66073633824afa70653dbc5fa4",
          "sha1": "b26053546fff009761942cbbcc4423a3a43cc153",
          "md5": "a040f994623a3f8eeb48cfa29a28a7c6"
        }
      ]
    }
  ]
}
