{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs.zeil",
    "module": "code-grader",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "code-grader-1.2.3.jar",
          "url": "code-grader-1.2.3.jar",
          "size": 120545,
          "sha512": "f63cda7809b7f529aa35460a4aaf2dc8ef8aeaa790dac9f10ed073ac43f21f4a9ce08c91ff88e3fa3c4ce7a6b41791d14849f1beee57e6479de3376b7dd8f289",
          "sha256": "63d6a7c78ec374d3e0daaf57856fa38ad229344248b6d76796d94732b1aa7ab8",
          "sha1": "ab60e88391dc0dfe328cea7831745ad3d418d880",
          "md5": "aa2d0a903f6f32612018f844612deeef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "5.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "code-grader-1.2.3.jar",
          "url": "code-grader-1.2.3.jar",
          "size": 120545,
          "sha512": "f63cda7809b7f529aa35460a4aaf2dc8ef8aeaa790dac9f10ed073ac43f21f4a9ce08c91ff88e3fa3c4ce7a6b41791d14849f1beee57e6479de3376b7dd8f289",
          "sha256": "63d6a7c78ec374d3e0daaf57856fa38ad229344248b6d76796d94732b1aa7ab8",
          "sha1": "ab60e88391dc0dfe328cea7831745ad3d418d880",
          "md5": "aa2d0a903f6f32612018f844612deeef"
        }
      ]
    }
  ]
}
