{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs.zeil",
    "module": "code-grader",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "code-grader-1.2.3.jar",
          "url": "code-grader-1.2.3.jar",
          "size": 120578,
          "sha512": "a701a4cf3991bbe572e4e5afd2751fcc1710775e1066dbf453fa4a95a78440f348f837eb6a095150b31c2ee38430153a5ca6c7301e38f82adc16bc7a80cda650",
          "sha256": "d45831a52cbf8d7c2de49f609470383f6f98525637fe2ba5ef5fdb0008bf7013",
          "sha1": "831871dab319439aa811f1268cc7f4884ce38f0e",
          "md5": "0f039b4fb96444ace77690202fdafa44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "5.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "code-grader-1.2.3.jar",
          "url": "code-grader-1.2.3.jar",
          "size": 120578,
          "sha512": "a701a4cf3991bbe572e4e5afd2751fcc1710775e1066dbf453fa4a95a78440f348f837eb6a095150b31c2ee38430153a5ca6c7301e38f82adc16bc7a80cda650",
          "sha256": "d45831a52cbf8d7c2de49f609470383f6f98525637fe2ba5ef5fdb0008bf7013",
          "sha1": "831871dab319439aa811f1268cc7f4884ce38f0e",
          "md5": "0f039b4fb96444ace77690202fdafa44"
        }
      ]
    }
  ]
}
