{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs.zeil",
    "module": "code-grader",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "code-grader-1.2.3.jar",
          "url": "code-grader-1.2.3.jar",
          "size": 120575,
          "sha512": "5c7a1d0122eba2feb86c0e9ad82a0c5fc4fec0b6addc57fa19c11a29da0488cb62c7d2c07edf9472fc2507090edb3beef9da361e094db6bb3d991df2fe67f7c0",
          "sha256": "37bc83077a5496330e9def05c70a59a62ef8305c465008cfc79a94903ee863ca",
          "sha1": "ab5239e7e040f534cc71bde3916f3a6241df5312",
          "md5": "92fd1761a65d12515340650e4828b95a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "5.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "code-grader-1.2.3.jar",
          "url": "code-grader-1.2.3.jar",
          "size": 120575,
          "sha512": "5c7a1d0122eba2feb86c0e9ad82a0c5fc4fec0b6addc57fa19c11a29da0488cb62c7d2c07edf9472fc2507090edb3beef9da361e094db6bb3d991df2fe67f7c0",
          "sha256": "37bc83077a5496330e9def05c70a59a62ef8305c465008cfc79a94903ee863ca",
          "sha1": "ab5239e7e040f534cc71bde3916f3a6241df5312",
          "md5": "92fd1761a65d12515340650e4828b95a"
        }
      ]
    }
  ]
}
