{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs",
    "module": "cowem-plugin",
    "version": "1.22.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cowem-plugin-1.22.4.jar",
          "url": "cowem-plugin-1.22.4.jar",
          "size": 1610918,
          "sha512": "f5313ad96e4718531cfc6e820b8a462fb9975ea386a990a1846525ffc1529bd1095a23d4482b2a039d4b5d38b6d989e9a03e7736011a3bbf87b1b5298af9dcce",
          "sha256": "3b973a9565d4a9f57fad8f5b5a5c4b30cb2b403f790c48654b8eff42b0f74556",
          "sha1": "9d56368827faa2947440e281151d973be063c8e8",
          "md5": "6961dd5a327a1182d1a6e0dbf669dfe4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hidetake",
          "module": "gradle-ssh-plugin",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.pegdown",
          "module": "pegdown",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "net.sf.saxon",
          "module": "Saxon-HE",
          "version": {
            "requires": "11.4"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.4.0.202211300538-r"
          }
        }
      ],
      "files": [
        {
          "name": "cowem-plugin-1.22.4.jar",
          "url": "cowem-plugin-1.22.4.jar",
          "size": 1610918,
          "sha512": "f5313ad96e4718531cfc6e820b8a462fb9975ea386a990a1846525ffc1529bd1095a23d4482b2a039d4b5d38b6d989e9a03e7736011a3bbf87b1b5298af9dcce",
          "sha256": "3b973a9565d4a9f57fad8f5b5a5c4b30cb2b403f790c48654b8eff42b0f74556",
          "sha1": "9d56368827faa2947440e281151d973be063c8e8",
          "md5": "6961dd5a327a1182d1a6e0dbf669dfe4"
        }
      ]
    }
  ]
}
