{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs",
    "module": "cowem-plugin",
    "version": "1.22.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cowem-plugin-1.22.4.jar",
          "url": "cowem-plugin-1.22.4.jar",
          "size": 1610905,
          "sha512": "c95e3811fe032f9ef006ff778d021bf185be8be0599e741ad5d22680a6c1dbba5134584d879b6db882d52abbf91f7978fc039088e542af5a965bc5a879b36354",
          "sha256": "7807bcb55e171a265e0b6a9d0e6fbed1ea8d983392df0dbec56779fe1e31e800",
          "sha1": "55f0fd00201cbde5a2c8a811beb04ec98f2ec88e",
          "md5": "ff25e09733a78854024cbc750aa61c32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hidetake",
          "module": "gradle-ssh-plugin",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.pegdown",
          "module": "pegdown",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "net.sf.saxon",
          "module": "Saxon-HE",
          "version": {
            "requires": "11.4"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.4.0.202211300538-r"
          }
        }
      ],
      "files": [
        {
          "name": "cowem-plugin-1.22.4.jar",
          "url": "cowem-plugin-1.22.4.jar",
          "size": 1610905,
          "sha512": "c95e3811fe032f9ef006ff778d021bf185be8be0599e741ad5d22680a6c1dbba5134584d879b6db882d52abbf91f7978fc039088e542af5a965bc5a879b36354",
          "sha256": "7807bcb55e171a265e0b6a9d0e6fbed1ea8d983392df0dbec56779fe1e31e800",
          "sha1": "55f0fd00201cbde5a2c8a811beb04ec98f2ec88e",
          "md5": "ff25e09733a78854024cbc750aa61c32"
        }
      ]
    }
  ]
}
