{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs",
    "module": "cowem-plugin",
    "version": "1.22.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cowem-plugin-1.22.4.jar",
          "url": "cowem-plugin-1.22.4.jar",
          "size": 1610903,
          "sha512": "e91b305304f96dc66d8c9e8d650d336826ddfb51804f3687d552e5f85ce05009d59c0ca6d8f5924dfef4f64ea2c7b9509a16b34d06eedfb115bfedb86fa2b7c1",
          "sha256": "567182a3ca787d583526b30433ee1ecaf0d5022e1d852709309f4a2941ba874b",
          "sha1": "b538a606a29452e769b453b7805bbbf0306ebfa1",
          "md5": "2cb556536869b82423c5b90b5c207b3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hidetake",
          "module": "gradle-ssh-plugin",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.pegdown",
          "module": "pegdown",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "net.sf.saxon",
          "module": "Saxon-HE",
          "version": {
            "requires": "11.4"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.4.0.202211300538-r"
          }
        }
      ],
      "files": [
        {
          "name": "cowem-plugin-1.22.4.jar",
          "url": "cowem-plugin-1.22.4.jar",
          "size": 1610903,
          "sha512": "e91b305304f96dc66d8c9e8d650d336826ddfb51804f3687d552e5f85ce05009d59c0ca6d8f5924dfef4f64ea2c7b9509a16b34d06eedfb115bfedb86fa2b7c1",
          "sha256": "567182a3ca787d583526b30433ee1ecaf0d5022e1d852709309f4a2941ba874b",
          "sha1": "b538a606a29452e769b453b7805bbbf0306ebfa1",
          "md5": "2cb556536869b82423c5b90b5c207b3f"
        }
      ]
    }
  ]
}
