{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs",
    "module": "cowem-plugin",
    "version": "1.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cowem-plugin-1.24.1.jar",
          "url": "cowem-plugin-1.24.1.jar",
          "size": 1594135,
          "sha512": "01c6a7add484ed8b95ca7d046ba37cb467c541ce9c5867b1cc11d9573c6781a6dc1045cdc71afc2311ec4901cdc23d5aaa27134f263db7f7ff93ef49aaec8ed7",
          "sha256": "110de704abf3f0fc0e831ed7413c86a605acf3d317849aaa7ffddbe3e0d45bd1",
          "sha1": "f1f00e81870aab325e4ac79d2c9a5d51a4645796",
          "md5": "09fb992b836db7d8f63a123d9a100625"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hidetake",
          "module": "gradle-ssh-plugin",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.pegdown",
          "module": "pegdown",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "net.sf.saxon",
          "module": "Saxon-HE",
          "version": {
            "requires": "11.4"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.4.0.202211300538-r"
          }
        }
      ],
      "files": [
        {
          "name": "cowem-plugin-1.24.1.jar",
          "url": "cowem-plugin-1.24.1.jar",
          "size": 1594135,
          "sha512": "01c6a7add484ed8b95ca7d046ba37cb467c541ce9c5867b1cc11d9573c6781a6dc1045cdc71afc2311ec4901cdc23d5aaa27134f263db7f7ff93ef49aaec8ed7",
          "sha256": "110de704abf3f0fc0e831ed7413c86a605acf3d317849aaa7ffddbe3e0d45bd1",
          "sha1": "f1f00e81870aab325e4ac79d2c9a5d51a4645796",
          "md5": "09fb992b836db7d8f63a123d9a100625"
        }
      ]
    }
  ]
}
