{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs.algae",
    "module": "algae-client-server",
    "version": "4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "algae-client-server-4.7.jar",
          "url": "algae-client-server-4.7.jar",
          "size": 440250,
          "sha512": "4c1eac0d81c0192dc19008335ce030d99471bfd5395f685a9c799d59d4757f7d02470cbce2f59c8969318a88ece2d02131d823f07eb014b5305ddd157a28683d",
          "sha256": "960b5cdc1e9c1e5886ea71e79a00cad44df9f72d036bd99e5899c0bc17b94971",
          "sha1": "be4e0dfcdb167516122afac442522e0334202fec",
          "md5": "b3d2e6ec4f5dfbb220661c0e0bb9c3bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "javax.help",
          "module": "javahelp",
          "version": {
            "requires": "2.0.05"
          }
        }
      ],
      "files": [
        {
          "name": "algae-client-server-4.7.jar",
          "url": "algae-client-server-4.7.jar",
          "size": 440250,
          "sha512": "4c1eac0d81c0192dc19008335ce030d99471bfd5395f685a9c799d59d4757f7d02470cbce2f59c8969318a88ece2d02131d823f07eb014b5305ddd157a28683d",
          "sha256": "960b5cdc1e9c1e5886ea71e79a00cad44df9f72d036bd99e5899c0bc17b94971",
          "sha1": "be4e0dfcdb167516122afac442522e0334202fec",
          "md5": "b3d2e6ec4f5dfbb220661c0e0bb9c3bc"
        }
      ]
    }
  ]
}
