{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs.algae",
    "module": "algae-client-server",
    "version": "4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "algae-client-server-4.7.jar",
          "url": "algae-client-server-4.7.jar",
          "size": 312903,
          "sha512": "ab03d255a6ba1b8f411e911667b295b005dc9d090dd725761132409dfd4a6e74e98bd10bf09f94142c1113817868661abace0eb42ecceeab48eb9bfa174279d9",
          "sha256": "9f222ab1d2845a5abe934fdbb8e4d2df05d305f88d88529712d1f737f44e7745",
          "sha1": "d9ceb4843f41e76f6b6f7cdb2e3c2018702b1131",
          "md5": "36cde03f5de9be131ea0e23e25c0410a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "javax.help",
          "module": "javahelp",
          "version": {
            "requires": "2.0.05"
          }
        }
      ],
      "files": [
        {
          "name": "algae-client-server-4.7.jar",
          "url": "algae-client-server-4.7.jar",
          "size": 312903,
          "sha512": "ab03d255a6ba1b8f411e911667b295b005dc9d090dd725761132409dfd4a6e74e98bd10bf09f94142c1113817868661abace0eb42ecceeab48eb9bfa174279d9",
          "sha256": "9f222ab1d2845a5abe934fdbb8e4d2df05d305f88d88529712d1f737f44e7745",
          "sha1": "d9ceb4843f41e76f6b6f7cdb2e3c2018702b1131",
          "md5": "36cde03f5de9be131ea0e23e25c0410a"
        }
      ]
    }
  ]
}
