{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs.zeil",
    "module": "code-grader",
    "version": "1.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "code-grader-1.2.7.jar",
          "url": "code-grader-1.2.7.jar",
          "size": 121178,
          "sha512": "a8652afb8bca6f5e175b433d671c00e389242cec6793e30777241814d33e8985f78550cce5c4e514d0baa28f0d5093ed4a551b848d06651f32d4478760acfc9c",
          "sha256": "3dcfa32339caad72dd33921a5a175d35307c53f15dabed189da8e1684a83463b",
          "sha1": "8b2ddaaa48e79be371c1411dea7e004b27295cb6",
          "md5": "9943eec0e92b44d1a0c60fe26bcb6375"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "5.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "code-grader-1.2.7.jar",
          "url": "code-grader-1.2.7.jar",
          "size": 121178,
          "sha512": "a8652afb8bca6f5e175b433d671c00e389242cec6793e30777241814d33e8985f78550cce5c4e514d0baa28f0d5093ed4a551b848d06651f32d4478760acfc9c",
          "sha256": "3dcfa32339caad72dd33921a5a175d35307c53f15dabed189da8e1684a83463b",
          "sha1": "8b2ddaaa48e79be371c1411dea7e004b27295cb6",
          "md5": "9943eec0e92b44d1a0c60fe26bcb6375"
        }
      ]
    }
  ]
}
