{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs.zeil",
    "module": "code-grader",
    "version": "1.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "code-grader-1.2.7.jar",
          "url": "code-grader-1.2.7.jar",
          "size": 121179,
          "sha512": "a2a61262e8d31251c86442c8aa2e0b55887509031fd1fe0287f9812326bb0cfb03cd960f32206e545bb2d2a6a67df7852c91238fbf6ea6f2388da6b7a5b78a0f",
          "sha256": "b1c928c2777b3120515747a31fe8fe4eee80a3b9202c061827d3938ee4b7237e",
          "sha1": "c67a6b4f3d3cb9d80b453d8fb5efdf123ceffa8f",
          "md5": "7bcabd43f535f57ad795104ec95d3e19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "5.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "code-grader-1.2.7.jar",
          "url": "code-grader-1.2.7.jar",
          "size": 121179,
          "sha512": "a2a61262e8d31251c86442c8aa2e0b55887509031fd1fe0287f9812326bb0cfb03cd960f32206e545bb2d2a6a67df7852c91238fbf6ea6f2388da6b7a5b78a0f",
          "sha256": "b1c928c2777b3120515747a31fe8fe4eee80a3b9202c061827d3938ee4b7237e",
          "sha1": "c67a6b4f3d3cb9d80b453d8fb5efdf123ceffa8f",
          "md5": "7bcabd43f535f57ad795104ec95d3e19"
        }
      ]
    }
  ]
}
