{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.odu.cs",
    "module": "cowem-plugin",
    "version": "1.22.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cowem-plugin-1.22.5.jar",
          "url": "cowem-plugin-1.22.5.jar",
          "size": 1610914,
          "sha512": "5e349576daf698f0ef240bb92674bc786a6d76ffd46eb99b73c5e48e0182b4953ab21ac711d60b36f4b5d35156e273fe82f83ef214cfb2ead778debdfd9a60b5",
          "sha256": "6137ebe6f6c05153c95586e71d50e70e10766bee206184b5fb5e01f44fa3cf6a",
          "sha1": "b617b87d91b384b5610fe988867972adec261cdc",
          "md5": "73748ac243527c60a6905406a184cede"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hidetake",
          "module": "gradle-ssh-plugin",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.pegdown",
          "module": "pegdown",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "net.sf.saxon",
          "module": "Saxon-HE",
          "version": {
            "requires": "11.4"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.4.0.202211300538-r"
          }
        }
      ],
      "files": [
        {
          "name": "cowem-plugin-1.22.5.jar",
          "url": "cowem-plugin-1.22.5.jar",
          "size": 1610914,
          "sha512": "5e349576daf698f0ef240bb92674bc786a6d76ffd46eb99b73c5e48e0182b4953ab21ac711d60b36f4b5d35156e273fe82f83ef214cfb2ead778debdfd9a60b5",
          "sha256": "6137ebe6f6c05153c95586e71d50e70e10766bee206184b5fb5e01f44fa3cf6a",
          "sha1": "b617b87d91b384b5610fe988867972adec261cdc",
          "md5": "73748ac243527c60a6905406a184cede"
        }
      ]
    }
  ]
}
